### ISSUE TITLE
Omitting mysql deploy causes app deploy to fail

### ISSUE THREAD

**Issue by jldec** [simple-starters/generator-k8s-simple#2]
It should be possible to leave out the mysql part of this generator when an app does not need a DB.
Going through just the application build and deploy (e.g. with the hello-fun starter) results in the following error:

```
Warning  Failed  12m (x324 over 82m)    kubelet, docker-desktop  Error: secret "mysql" not found
 ```

This appears to be caused by some `secretKeyRef` in the `deployment.yaml`
```yaml
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql
                key: mysql-password
```
